apiVersion: v1
kind: PersistentVolume
metadata:
  name: pidev-uploads-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.216.128
    path: /var/lib/pidev/uploads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pidev-uploads-pvc
  namespace: pidev-prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: pidev-uploads-pv
